portfolio/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'portfolio'
urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path('projects', views.ProjectListView.as_view(), name='project-list'),
    path(
        'project/<slug:slug>/', views.ProjectDetailView.as_view(),
        name='project-detail'),
    path('contact/', views.contact_view, name='contact'),
    path(
        'experience/', views.ExperienceListView.as_view(),
        name='experience-list'),
    path('gist/', views.NoteListView.as_view(), name='note-list'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/urls.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from portfolio.views import Error404

urlpatterns = [
    path('yuyutsu/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico',RedirectView.as_view(url='/static/images/favicon.ico')),
]

handler404 = Error404.get_rendered_view()

portfolio/models.py
# -*- coding: utf-8 -*-
from django.db import models
import datetime
import readtime
from django.utils import timezone
from django.utils.text import slugify
from ckeditor.fields import RichTextField


class Projects(models.Model):
    """
    Project model
    """
    CATEGORY_CHOICES = (
        ('Web Apps', 'Web Apps'),
        ('Machine Learning', 'Machine Learning'),
        ('APIs', 'APIs'),
        ('Command Line Applications', 'Command Line Applications'),
        ('Data Visualization', 'Data Visualization'),
        ('Graphical User Interfaces', 'Graphical User Interfaces'),
        ('Artificial Intelligence', 'Artificial Intelligence'),
        ('DevOps', 'DevOps'),
        ('Data Science', 'Data Science'),
        ('Other', 'Other'),
    )
    title = models.CharField(max_length=255)
    summary = models.TextField(max_length=1000, blank=True)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    category = models.CharField(
        max_length=50, choices=CATEGORY_CHOICES,
        default='Other')
    urllink = models.URLField(max_length=255)
    startdate = models.DateField()
    enddate = models.DateField(blank=True, null=True)
    technology = models.CharField(max_length=255)
    sourcecode = models.URLField(max_length=255)
    description = RichTextField()
    image = models.URLField(max_length=500, blank=True, null=True)
    publish = models.BooleanField(default=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Projects, self).save(*args, **kwargs)

    def get_readtime(self):
        result = readtime.of_text(self.description)
        return result.text

    class Meta:
        verbose_name = "Project Entry"
        verbose_name_plural = "Project Entries"
        ordering = ["category", "-pub_date"]


class AwardsAndAchievements(models.Model):
    """
    Award and Achievements
    """
    title = models.CharField(max_length=255)
    received = models.DateField()

    def __str__(self):
        return self.title

    def get_formated_date(self):
        """
        Returns the date in the format of 'Month Year'
        """
        return self.received.strftime('%B %Y')

    class Meta:
        verbose_name = "Award and Achievement Entry"
        verbose_name_plural = "Award and Achievement Entries"


class Notes(models.Model):
    """
    Notes are stored in the database as a text field.
    """
    note = models.CharField(max_length=255)
    description = RichTextField()
    tags = models.CharField(max_length=255, blank=True)
    gisturl = models.URLField(max_length=255)

    def __str__(self):
        return self.note

    class Meta:
        verbose_name = "Note Entry"
        verbose_name_plural = "Note Entries"


class Summary(models.Model):
    """
    Summary is a single line of text that summarizes the projects.
    """
    summary = RichTextField()
    summary_image = models.URLField(max_length=500, blank=True)

    def __str__(self):
        return self.summary

    class Meta:
        verbose_name = "Summary Entry"
        verbose_name_plural = "Summary Entries"


class Experience(models.Model):
    """
    Experience details.
    """
    title = models.CharField(max_length=255)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    experience = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Experience Entry"
        verbose_name_plural = "Experience Entries"


class Contact(models.Model):
    """
    Contact is a single line of text that summarizes the projects.
    """
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message_date = models.DateTimeField(auto_now_add=True)
    message = models.TextField()

    def __str__(self):
        return self.email

portfolio/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from .models import Contact
from django import forms

class ContactForm(ModelForm):
    """
    Contact form for the contact page.
    """
    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {
          'message': forms.Textarea(attrs={'rows':2}),
        }

portfolio/views.py
# -*- coding: utf-8 -*-
import os
from .models import Projects, AwardsAndAchievements, Notes,\
    Summary, Experience
from django.utils import timezone
from django.views import generic
from .forms import ContactForm
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.core.mail import send_mail
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from htmlmin.decorators import minified_response
from django.views.generic import TemplateView


class IndexListView(generic.ListView):
    """
    Index view for the portfolio.
    """
    context_object_name = 'project_list'
    template_name = 'portfolio/index.html'
    queryset = Projects.objects.order_by('-pub_date')[:3]

    def get_context_data(self, **kwargs):
        context = super(IndexListView, self).get_context_data(**kwargs)
        context['award_list'] = AwardsAndAchievements.objects.order_by('-received')
        context['summary_list'] = Summary.objects.all()
        return context


class ProjectListView(generic.ListView):
    context_object_name = 'project_list'
    template_name = 'portfolio/project_list.html'

    def get_queryset(self):
        """Return the projects"""
        return Projects.objects.order_by('-pub_date')


class NoteListView(generic.ListView):
    context_object_name = 'note_list'
    template_name = 'portfolio/note.html'

    def get_queryset(self):
        """Return the Notes"""
        return Notes.objects.all()


class ProjectDetailView(generic.DetailView):
    model = Projects
    template_name = 'portfolio/project_detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        context['now'] = timezone.now()
        return context


class ExperienceListView(generic.ListView):
    context_object_name = 'experience_list'
    template_name = 'portfolio/experience.html'

    def get_queryset(self):
        """Return the experience"""
        return Experience.objects.order_by('-start_date')


@minified_response
@csrf_exempt
def contact_view(request):
    message = ""
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            sub = form.cleaned_data["subject"][:min(len(form.cleaned_data["subject"]),20)] + '...'
            email_subject = f'YUYU: {form.cleaned_data["email"]}: {sub}'
            email_message = form.cleaned_data['message']
            message = Mail(
                from_email=settings.CONTACT_EMAIL,
                to_emails=settings.ADMIN_EMAIL + form.cleaned_data["email"].split(' '),
                subject=email_subject,
                html_content=email_message)
            try:
                sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
                sg.send(message)
                # send_mail(email_subject, email_message, settings.CONTACT_EMAIL, settings.ADMIN_EMAIL)    
                print('Email sent')
                message = 'Your message has been sent. Thank you!'
            except Exception as e:
                print(e.message)         
                message = 'Your message could not be sent. Please try again later.'
    form = ContactForm()
    context = {'form': form, 'message': message}
    return render(request, 'portfolio/contact.html', context)



class Error404(TemplateView):
    template_name = "portfolio/404.html"
    
    @classmethod
    def get_rendered_view(cls):
        as_view_fn = cls.as_view()

        def view_fn(request, exception):
            response = as_view_fn(request)
            # this is what was missing before
            response.render()
            return response
        return view_fn

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        response.status_code = 404
        return self.render_to_response({'status_code': response.status_code})

portfolio/templates/portfolio/includes/awards.html
<div id="achievements" class="ui text container">
  <p class="ui text center aligned header" style="font-size: 3em; margin: 0em;padding-bottom: 0em !important ">
    Awards and Achievements
  </p>
  <div class="ui horizontal divider">
    <i class="ui code icon"></i>
  </div>
</div>
<div class="ui container" style="padding-top: 0em;">
  <div class="ui relaxed divided list">
    <div class="ui piled raised segment">
      <div class="ui four column padded grid">
        <div class="large screen only sixteen wide column">
          <div class="ui three doubling cards">
            {% if award_list %}
            {% for award in award_list %}
            <div class="card">
              <div class="ui link huge list" style="color: rgb(61, 61, 61) !important;">
                <a class="item">{{ award.title }} </a>
              </div>
              <div class="ui small bottom right attached label">{{ award.received|date:"Y F" }}</div>
            </div>
            {% endfor %}
            {% else %}
            <p>No detail are available.</p>
            {% endif %}
          </div>
        </div>
        <div class="tablet only mobile only sixteen wide column">
          <div class="ui one doubling cards">
            {% if award_list %}
            {% for award in award_list %}
            <div class="card">
              <div class="ui big link list">
                <a class="item">{{ award.title }} </a>
              </div>
              <div class="ui small bottom right attached label">{{ award.received|date:"Y F" }}</div>
            </div>
            {% endfor %}
            {% else %}
            <p>No detail are available.</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

portfolio/templates/portfolio/includes/back_button.html
<div style="position:fixed;margin:2em;bottom:0;left:0;animation:flash 2s ease-in-out infinite;z-index:6;" >
    <a href="/" class="ui raised segment button" style="background: linear-gradient(90deg, rgb(187, 185, 185) 0%, rgb(255, 255, 255) 100%);">Home</a>
</div>

portfolio/templates/portfolio/includes/banner.html
{% load static %}
<div class="ui four column padded grid">
  <div class="ui large screen only eight wide left aligned column">
    <pre class="ui massive header" style="font-size:2.3em; padding: 5% ;font-family: Courier;margin-top: 10%; color: #005C00">
  def about_me():
      '''
      Software Developer...
      I Love working with
      Python Ecosystem
      '''
      return  <span class="ui icons right link"><a href="https://github.com/raahoolkumeriya" target="_blank" aria-label="github" class="ui item"><i class="github large icon" style="color: #005C00"></i></a>
    <a href="https://twitter.com/KumeriyaRahul" target="_blank" aria-hidden="true"  class="item"><i
        class="twitter large icon" style="color: #005C00"></i></a>
    <a href="https://rahulkumeriya.medium.com" target="_blank" aria-hidden="true" class="item">
      <i class="medium large icon" style="color: #005C00"></i></a>
    <a href="https://www.linkedin.com/in/rahulkumeriya" target="_blank" aria-hidden="true" class="item"><i
        class="linkedin large icon" style="color: #005C00"></i></a>
    </span>
    </pre>
  </div>
  <div class="ui large screen only eight wide column">
    <div class="six wide right floated column center aligned">
      <img class="ui centered massive image" src="{% static 'images/developer_activity.svg' %}"
        alt="developer_activity-image" height=50% width=50%>
    </div>
  </div>
  <div class="tablet only mobile only sixteen wide column">
    <div class="ui equal width center aligned padded grid">
      <div class="row">
        <div class="column">
<pre class="ui header" style="font-size: 1.6em; padding-top: 10px;padding-bottom: 10px; font-family: Courier;color: rgb(61, 61, 61) !important;">
def about_me():&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    '''&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Software Developer...
    I Love working with&nbsp;&nbsp;
    Python Ecosystem&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    '''&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    return <span class="ui right link">
      <a href="https://github.com/raahoolkumeriya" target="_blank"
        aria-label="github" class="ui item"><i class="github large icon" style="color: rgb(61, 61, 61) !important;"></i></a>
      <a href="https://twitter.com/KumeriyaRahul" aria-label="twitter" target="_blank" class="item"><i
          class="twitter large icon" style="color: rgb(61, 61, 61) !important;"></i></a>
      <a href="https://rahulkumeriya.medium.com" aria-label="medium" target="_blank" class="item">
        <i class="medium large icon" style="color: rgb(61, 61, 61) !important;"></i></a>
      <a href="https://www.linkedin.com/in/rahulkumeriya"  aria-label="linkedin" target="_blank" class="item"><i
          class="linkedin large icon" style="color: rgb(61, 61, 61) !important;"></i></a>
      </span>
  </pre>      
        </div>
      </div>
    </div>
     <div class="ui column grid">
      <div class="column">
          <img class="ui centered large rounded image" src="{% static 'images/dev_productivity.svg' %}" width="50%"
          height="50%" alt="dev-productivity-image-2">
      </div>
     </div>
  </div>
</div>

portfolio/templates/portfolio/includes/footer.html
<div class="ui hidden divider"></div>
<div class="ui vertical fluid footer" style="margin-bottom: 0%; margin-top: 0%; background-color: #dad8d8; color:rgb(66, 65, 65) !important;" >
  <div class="ui column grid">
    <div class="mobile only sixteen wide column center aligned">
        <div class="ui link massive list">
          <a class="ui item" href="https://linktr.ee/rahulkumeriya">connect.me</a>
          <span style="font-size:small;">version 2.0.2 महारथी कर्ण</span>
        </div>
        <div class="ui link big list">
          <a class="item">©2021 Rahul Kumeriya. All right reserved.</a>
          <p>All illustrations on this website are my own work and are subject to copyright.</p>
        </div>
      </div>
      <div class="ui stackable height stackable grid computer only two column row">
        <div class="column center aligned">
          <div class="ui link massive list seven wide column">
            <div class="ui hidden divider"></div>
            <a class="item" href="https://linktr.ee/rahulkumeriya">connect.me</a>
            <span style="font-size:small;">version 2.0.2 महारथी कर्ण</span>
          </div>
        </div>
        <div class="ui column center aligned">
            <div class="ui link big list seven wide column">
              <div class="ui hidden divider"></div>
              <a class="item">©2021 Rahul Kumeriya. All right reserved.</a>
              <p>All illustrations on this website are my own work and are subject to copyright.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

portfolio/templates/portfolio/includes/js.html
{% load compress %}
{% compress js %}
<div id="disqus_thread"></div>
<script>
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://https-rahulkumeriya-herokuapp-com.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
{% endcompress %}

portfolio/templates/portfolio/includes/menu.html
{% load static %}
<div class="ui four column padded grid" style="width: auto !important; padding: 2em;">
  <div class="mobile only sixteen wide stackable column">
    <div class="ui fixed labeled link tiny icon six item menu">
      <a class="active item" href="/"><i aria-hidden="true" class="ui home icon"></i>Home</a>
      <a class="item" href="{% url 'portfolio:project-list' %}"><i aria-hidden="true" class="th list icon"></i>Projects</a>
      <a class="item" href="{% url 'portfolio:experience-list' %}"><i aria-hidden="true" class="phoenix framework icon"></i>Experience</a>
      <a class="item" href="{% url 'portfolio:note-list' %}"><i aria-hidden="true" class="object ungroup icon"></i>Gist</a>
      <a class="item" href="{% url 'portfolio:contact' %}"><i aria-hidden="true" class="envelope open outline icon"></i>Contact</a>
    </div>
  </div>
  <div class="computer only one column row">
    <div class="column">
      <div class="ui massive link list secondary menu">
        <a class="ui active item raised inverted" href="/">__rahul_kumeriya__</a>
        <div class="right menu">
          <a class="item inverted" href="{% url 'portfolio:project-list' %}" style="animation:flash 1.5s ease-in-out infinite;">
            <i class="flag green icon"></i>Projects</a>
          <a class="item inverted" href="{% url 'portfolio:experience-list' %}">Experience</a>
          <a class="item inverted" href="{% url 'portfolio:note-list' %}">Gist</a>
          <a class="item inverted" href="https://docs.google.com/document/d/1aeDuwuT_fwPFJxc80L2BTWPmobYejq1lXNL7ccZJt3w/edit?usp=sharing" target="_blank">Resume</a>
          <a class="item inverted" href="{% url 'portfolio:contact' %}">Contact</a>
        </div>
      </div>
    </div>
  </div>
</div>

portfolio/templates/portfolio/includes/projects.html
{% load static %}
<div id="projects" class="ui center aligned">    
    <div class="ui text container" style="padding-top: 0em;">
      <p class="ui text center aligned header"
        style="font-size: 3em; margin-bottom: 0em;padding-bottom: 0em !important ">
        Noteworthy Projects
    </p>
      <div class="ui horizontal divider">
        <i class="ui code icon"></i>
      </div>
  </div>
  <div class="ui stripe community vertical container">
    <div class="ui three column center aligned divided very relaxed stackable grid container">
      <div class="row">
        {% if project_list %}
        {% for project in project_list %}
          <div class="column">
            <a href="{% url 'portfolio:project-detail' project.slug %}">
              <div class="ui disabled image">
                <img class="ui medium image" width="50%" height="50%"
                src="{% if project.image %} 
                      {{ project.image }} 
                    {% else %} 
                      {% static 'images/default.svg' %} 
                    {% endif %}" alt="project-detail-image-{{ forloop.counter }}">
              </div>
              <h2 class="ui header">
                {{ project.title }}
              </h2>
            </a>
            <div class="ui hidden divider"></div>
          <p>{{ project.summary }}</p>
          </div>
        {% endfor %}
        {% else %}
        <p>No project are available.</p>
        {% endif %}
      </div>
    </div>
  </div>
  
  <div class="fluid ui buttons" style="padding-top: 0%;">
    <a href="{% url 'portfolio:project-list' %}" style="background: linear-gradient(200deg, rgb(187, 185, 185) 0%, rgb(255, 255, 255) 100%);" class="ui raised segment text container button">
      View All Projects
    </a>
  </div>
</div>

portfolio/templates/portfolio/includes/skills.html
{% load static %}
<div id="skills" class="ui center aligned">
  <div class="ui text link container">
      <p class="ui text center aligned header" style="font-size: 3em; margin-bottom: 0em;padding-bottom: 0em !important ">
        Skills & Tools
      </p>
      <div class="ui horizontal divider">
          <i class="ui code icon"></i>
        </div>
  </div>
    <div class="ui stripe community vertical">
      <div class="ui four column center aligned very relaxed stackable grid container">
        <div class="row">
          <div class="column">
            <h2 class="ui icon medium header">
              <i class="tasks icon"></i>
              programming languages
            </h2>
            <p>Python, Shell Script, PLSQL</p>
          </div>
          <div class="column">
            <h2 class="ui icon medium header">
              <i class="database icon"></i>
              databases
            </h2>
            <p>Oracle, MonogoDB, MySQL, Postgres</p>
          </div>
          <div class="column">
            <h2 class="ui icon medium header">
              <i class="braille icon"></i>
              frameworks
            </h2>
            <p>Streamlit, Django, Flask, FastAPI, GitHub</p>
          </div>
          <div class="column">
            <h2 class="ui icon medium header">
              <i class="cogs icon"></i>
              tools
            </h2>
            <p>Ansible, CICD, Sciket-Learn, Cloud (Azure, Heroku)</p>
          </div>
        </div>
      </div>
    </div>
    <div class="ui stripe community vertical">
      <div class="ui four column center aligned very relaxed stackable grid container">
        <div class="row">
          <div class="column">
            <h2 class="ui icon medium header">
              <i class="bolt icon"></i>
              comfortable with
            </h2>
            <p>Data Science, Machine Learning</p>
          </div>
          <div class="column">
            <h2 class="ui icon medium header">
              <i class="tint icon"></i>
              intrested in
            </h2>
            <p>Deep Learning, AI</p>
          </div>
        </div>
      </div>
    </div>
  </div>

portfolio/templates/portfolio/includes/summary.html
{% load static %}
<div class="ui stripe community vertical container">
    <div class="ui three column center aligned divided very relaxed stackable grid container">
      <div class="row">
        {% if summary_list %}
        {% for item in summary_list %}
        <div class="ui column">
          <div class="ui disabled image">
            <img class="ui medium image" height="50%" width="50%" src="{% if item.summary_image %}
            {{ item.summary_image }}
            {% else %}
              {% static 'images/design.svg' %}
            {% endif %}"
              alt="design-{{ forloop.counter }}">
          </div>
          <div class="ui hidden divider"></div>
          <p>
            {{ item.summary|safe }}
          </p>
        </div>
        {% endfor %}
        {% else %}
        <div class="column">
          <div class="ui image">
            <img class="ui small image" src="{% static 'images/void.svg' %}" alt="null-image">
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>